# define variables
@GameID = 8fdf0d9f-9f1c-441e-b877-dc80e7cc7e17

### Get all games
GET http://localhost:8080/api/games/

### Get a game by ID
GET http://localhost:8080/api/games/{{GameID}}

### Create a new game
POST http://localhost:8080/api/games/
Content-Type: application/json

{
  "title": "The Witcher 3",
  "description": "An open-world RPG set in a fantasy universe.",
  "genres": [
    "RPG",
    "ADVENTURE"
  ]
}

### Update an existing game
PUT http://localhost:8080/api/games/{{GameID}}
Content-Type: application/json

{
  "title": "The Witcher 3: Wild Hunt",
  "description": "An open-world RPG set in a fantasy universe with enhanced graphics.",
  "genres": [
    "RPG",
    "ADVENTURE",
    "ACTION"
  ]
}

### Change game status
PATCH http://localhost:8080/api/games/{{GameID}}/status?value=INACTIVE
Content-Type: application/json

### Change game status back to ACTIVE
PATCH http://localhost:8080/api/games/{{GameID}}/status?value=ACTIVE
Content-Type: application/json

### Delete a game
DELETE http://localhost:8080/api/games/{{GameID}}