# define variables
@GameID = 587ecb9c-f600-422d-8ad9-eaeb44930616

### Get all games
GET http://localhost:8080/api/games/

### Get a game by ID
GET http://localhost:8080/api/games/{{GameID}}


### Get most popular games stats
GET http://localhost:8080/api/games/stats/popular


### Create a new game
POST http://localhost:8080/api/games/
Content-Type: application/json

{
  "title": "Test Game",
  "description": "A test game description.",
  "genres": [
    "RPG",
    "ADVENTURE",
    "OTHER"
  ]
}

### Update an existing game
PUT http://localhost:8080/api/games/{{GameID}}
Content-Type: application/json

{
  "title": "Updated test game title",
  "description": "An updated test game description.",
  "genres": [
    "RPG",
    "ADVENTURE",
    "ACTION"
  ]
}

### Change game status
PATCH http://localhost:8080/api/games/{{GameID}}/status?value=INACTIVE
Content-Type: application/json

### Change game status back to ACTIVE
PATCH http://localhost:8080/api/games/{{GameID}}/status?value=ACTIVE
Content-Type: application/json

### Delete a game
DELETE http://localhost:8080/api/games/{{GameID}}

### Get game pupolarity stats
GET http://localhost:8080/api/games/stats/popular

### Get popular games
GET http://localhost:8080/api/games/popular