@PlayerID=03993380-2e13-48e9-a2f0-98e87dbf4004

### Get all players
GET http://localhost:8080/api/players/

### Fetch players with their loved games
### Get all players
GET http://localhost:8080/api/players/?lovedGames=true

### Get a player by ID
GET http://localhost:8080/api/players/{{PlayerID}}

### Create a new player
POST http://localhost:8080/api/players/
Content-Type: application/json

{
  "username": "TestPlayer",
  "email": "gamer@example.com",
  "firstName": "John",
  "lastName": "Doe"
}

### Create another player
POST http://localhost:8080/api/players/
Content-Type: application/json

{
  "username": "ProGamer",
  "email": "progamer@example.com",
  "firstName": "Jane",
  "lastName": "Smith"
}

### Update player information
PUT http://localhost:8080/api/players/{{PlayerID}}
Content-Type: application/json

{
  "username": "ProGamer",
  "email": "test@example.com",
  "firstName": "Johnathan",
  "lastName": "Doe"
}

### Delete a player by ID
DELETE http://localhost:8080/api/players/{{PlayerID}}


### love a game
PATCH http://localhost:8080/api/players/{{PlayerID}}/games/f0a1b2c3-d4e5-4f5a-7b8c-9d0e1f2a3b4c/love

### Love another game
PATCH http://localhost:8080/api/players/{{PlayerID}}/games/f6a7b8c9-d0e1-4f5a-3b4c-5d6e7f8a9b0c/love

### unlove a game
PATCH http://localhost:8080/api/players/{{PlayerID}}/games/f0a1b2c3-d4e5-4f5a-7b8c-9d0e1f2a3b4c/unlove