@PlayerID=5a371e00-57fb-4e9f-a816-96d385aef64d

### Get all players
GET http://localhost:8080/api/players/

### Fetch players with their loved games
### Get all players
GET http://localhost:8080/api/players/?lovedGames=true

### Get a player by ID
GET http://localhost:8080/api/players/{{PlayerID}}

### Create a new player
POST http://localhost:8080/api/players/
Content-Type: application/json

{
  "username": "Gamer123",
  "email": "gamer@example.com",
  "firstName": "John",
  "lastName": "Doe"
}

### Create another player
POST http://localhost:8080/api/players/
Content-Type: application/json

{
  "username": "ProGamer",
  "email": "progamer@example.com",
  "firstName": "Jane",
  "lastName": "Smith"
}

### Update player information
PUT http://localhost:8080/api/players/{{PlayerID}}
Content-Type: application/json

{
  "username": "ProGamer",
  "email": "test@example.com",
  "firstName": "Johnathan",
  "lastName": "Doe"
}

### Delete a player by ID
DELETE http://localhost:8080/api/players/{{PlayerID}}


### love a game
PATCH http://localhost:8080/api/players/{{PlayerID}}/games/6d32d996-69c8-4e7d-bf7c-30d06748ce5d/love